### ISSUE TITLE
python 2.6 not supported

### ISSUE THREAD

**Issue by MrMarvin** [tinyclues/saltpad#44]
I tried to run saltpad on a CentOS 6 machine. However it does not seem to be compatible with its python 2.6.6. Is this correct or am I missing something here?
```
(saltpadenv)[vagrant@master1-salt1 saltpad]$ python app.py
  File "app.py", line 221
    args = {k: v for (k, v) in request.form.iteritems() if not k in
                   ^
SyntaxError: invalid syntax
```
I have no issue running this on another machine with python 2.7.
If saltpad depends on python >= 2.7, this should be noted prominently in the README, I believe.

**Comment by Lothiraldan** [comment]
Yes, currently saltpad doesn't support python 2.6, someone has the same issue on the ML, I'm not sure if python 2.6 support is something difficult to achieve or if it's a big requirement for some people.

In your case, is python 2.6 support mandatory?

**Comment by Lothiraldan** [comment]
Btw you were right, I just amended the README to make it explicit: https://github.com/tinyclues/saltpad/commit/b2b12bcf2731864344b414def43a83db1fe58a56

**Comment by MrMarvin** [comment]
@Lothiraldan Good to know. I think there is a general need for python2.6 support. Saltstack itself runs fine on it and CentOS 6 is a very common OS these days. 

We should estimate how annoying it would be to be 2.6 compatible with SaltPad. My python is mediocre at best, but IMHO it should be too hard.

**Comment by Lothiraldan** [comment]
@MrMarvin I was not aware that SaltStack was compatible with Python 2.6, thank you, I will try to see how difficult is it to run saltpad on python 2.6, don't think it should be that hard.

**Comment by michael-kehoe** [comment]
I've ported it to Python 2.6 on Centos 6.5. Needs further testing. Unfortunately some of the Python isn't elegant, but it works. I'll try and put in a PR in the next week or so

**Comment by racooper** [comment]
I'll vote for 2.6 support. All my systems are CentOS 6 with stock python 2.6.6 installed.

**Comment by Lothiraldan** [comment]
@michael-kehoe Could you send a Pull-Request to see the amount of work done and start reviewing?

**Comment by racooper** [comment]
By the way, according to Salt docs (http://docs.saltstack.com/en/latest/topics/installation/index.html#dependencies):
Python 2.6 >= 2.6 <3.0

I would expect to see Python 2.6 for at least another 5 years since RHEL/CentOS 6 is supported until 2020.

**Comment by iggy** [comment]
That's the problem people are trying to solve with docker/containers/etc... But I agree... 2.6 is a worthy goal for now.

https://pypi.python.org/pypi/six is something that can help in this area (although it's meant for py2/py3 compatibility, it actually supports back to 2.5, so it can help with different versions of py2 as well)

**Comment by Inveracity** [comment]
I'd like to see support for 2.6 aswell :+1:

**Comment by Lothiraldan** [comment]
I just pushed a pull-request with some fixes for python 2.6, could you please give it a shot?

**Comment by Inveracity** [comment]
I'll try ASAP, thanks!

**Comment by Inveracity** [comment]
First off, my python skills are mediocre at best, so forgive any terrible suggestions I make regarding the code.

Secondly, I'm running python 2.6.9 on SLES11 SP3

Okay, so, here's what I've found:

__The original post is still a problem:__

  File "app.py", line 221
    args = {k: v for (k, v) in request.form.iteritems() if not k in
                   ^

I tried fixing this by doing:

    testv  = (v for (k, v) in request.form.iteritems() if not k in
        ('csrf_token', 'tgt', 'fun', 'expr_form', 'name', 'description') and v)
            
        args = {k: testv}

------
__and again at around line 292__

        testv = (v for (k, v) in request.form.iteritems() if not k in ('csrf_token', 'tgt', 'fun', 'expr_form') and v)
        args = {k: testv}

------
__Around line 73 it goes:__

        msg = 'Invalid permissions, saltpad needs {} for user {}'.format(perms, session['username'])
        flash(msg, 'error')
    else:
        flash('Hi {}'.format(form['username'].data))

It got all hot and bother by not having positional values in the brackets {}
so I changed those to:

        msg = 'Invalid permissions, saltpad needs {0} for user {1}'.format(perms, session['username'])
        flash(msg, 'error')
    else:
        flash('Hi {0}'.format(form['username'].data))

------
__Finally in the utils.py, another pesky for loop at around line 72__

    statuses = {False: 2, None: 1, True: 0}
    reverse_statues = {v: k for k, v in statuses.items()}
    human_status = {False: 'failure', None: 'warning', True: 'success'}

Had to initiate the v variable, and again break the loop into a twostep

    statuses = {False: 2, None: 1, True: 0}
    v = ""
    testk = (k for k, v in statuses.items())
    reverse_statues = {v: testk}
    human_status = {False: 'failure', None: 'warning', True: 'success'}

After that I logged in succesfully without any trouble (so far), it is very slow though, compared to running it on ubuntu with 2.7.x, but that's a whole different can of worms I imagine.

I hope this helps :)

**Comment by Lothiraldan** [comment]
@Inveracity Did you try with the branch of the PR `python_versions` because I fix them https://github.com/tinyclues/saltpad/pull/58/files#diff-825e7e4f8ac32c92cc17a0a064ca177a

**Comment by Inveracity** [comment]
Forgive me, I'm completely new to github, I'm not exactly sure how I get hold of a specific branch, I found this command git clone -b <branch> --single-branch <git repo>, but I'm not sure what goes into the <branch> part?

**Comment by Inveracity** [comment]
@Lothiraldan  Disregard that previous comment, ran run.py, and it seems to work
Thanks for your hard work! :)

**Comment by Lothiraldan** [comment]
@Inveracity If everything is fine, could you please close the issue?

**Comment by Inveracity** [comment]
@Lothiraldan it's not mine to close @MrMarvin is the OP

**Comment by Lothiraldan** [comment]
Yes sorry, @MrMarvin

**Comment by MrMarvin** [comment]
In the meantime we did upgrade machines on our side and now no longer run with Python 2.6 so for me the problem is gone. Still I believe that the changes here did the right thing and as @Inveracity reported work well. Thanks everyone!
