### ISSUE TITLE
Invalid Permissions, saltpad needs..

### ISSUE THREAD

**Issue by lukayeh** [tinyclues/saltpad#84]
Hi,

We are currently receiving the following error message:

Invalid Permissions, saltpad needs ['.*','@runner','@wheel'] for user lpage

However when you remove the /login from the url it has logged me in successfully.

I have performed the debug tasks and receive the following:

````
[root@pepper salt]# curl -i -H accept=application/json -d username=lpage -d password=lpage -d eauth=pam http://172.
HTTP/1.1 200 OK
Content-Length: 206
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/3.2.2
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Mon, 17 Aug 2015 13:06:39 GMT
Access-Control-Allow-Origin: *
X-Auth-Token: 5035735ed16360c2a8b073e614a65475dca34f13
Content-Type: application/json
Set-Cookie: session_id=5035735ed16360c2a8b073e614a65475dca34f13; expires=Mon, 17 Aug 2015 23:06:39 GMT; Path=/
`````
Salt version report below:
````

[root@pepper salt]# salt --versions-report
           Salt: 2015.5.0
         Python: 2.6.6 (r266:84292, Jul 23 2015, 05:13:40)
         Jinja2: 2.8
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
````

**Comment by Lothiraldan** [comment]
@lukayeh I just pushed a fix, indeed you were authenticated even without the right permissions. Theses permissions are validated on saltpad side because it need a specific set of permissions to works correctly, your salt-api setup seems correct.

Could you please test with master version?

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

We get the following error now:

KeyError 'username'

````
[root@pepper saltpad-master]# python run.py
 * Running on http://172.19.33.34:5000/
 * Restarting with reloader
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /login HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/css/bootstrap.css HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/css/sb-admin.css HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/font-awesome/css/font-awesome.min.css HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/css/saltpad.css HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/css/jsontree.css HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/css/dataTables.bootstrap.css HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/js/jquery-1.10.2.js HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/js/bootstrap.js HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/js/jsontree.js HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/js/jquery.dataTables.min.js HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/js/dataTables.bootstrap.js HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /static/font-awesome/fonts/fontawesome-webfont.woff?v=4.2.0 HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:53] "GET /favicon.ico HTTP/1.1" 404 -
172.19.33.34 - - [17/Aug/2015 16:50:57] "POST /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/saltpad-master/saltpad/app.py", line 78, in login
    msg = 'Invalid permissions, saltpad needs {0} for user {1}'.format(perms, session['username'])
  File "/usr/lib/python2.6/site-packages/werkzeug/local.py", line 368, in <lambda>
    __getitem__ = lambda x, i: x._get_current_object()[i]
KeyError: 'username'
172.19.33.34 - - [17/Aug/2015 16:50:57] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:57] "GET /login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:57] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:57] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:57] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:57] "GET /login?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
172.19.33.34 - - [17/Aug/2015 16:50:57] "GET /login?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
````

Any ideas?

**Comment by Lothiraldan** [comment]
Oups, could you try again with master version? I missed this line in my review.

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

We updated the app.py, however still getting the same error message?

When you say 'try again with master version' what does this mean?

Thanks,

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

I saw that another change had been made so updated the app.py we are now back to the original Invalid Permissions error message this time when removing /login it does not log me in.

Any ideas?

Does it make any difference that we're running run.py instead of app.py?

Thanks,

**Comment by Lothiraldan** [comment]
Hi @lukayeh, I pushed a new commit on the master branch of this repository with a fix.

The behavior you see with latest version is normal and intended, saltpad couldn't works without this specific set of permissions, not until salt works on this https://github.com/saltstack/salt/issues/21679. Is it possible for you to update the permission of this user?

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

We are more than happy to update permissions if it means we can access, would you be able to advise a working set of permissions our current looks like the following:
````
external_auth:
  pam:
    amonitor:
         - .*
         - '@jobs'
    hbaxter:
         - .*
         - '@wheel'   # to allow access to all wheel modules
         - '@runner'  # to allow access to all runner modules
         - '@jobs'    # to allow access to the jobs runner and/or wheel module
    tsembhi:
         - .*
         - '@wheel'   # to allow access to all wheel modules
         - '@runner'  # to allow access to all runner modules
         - '@jobs'    # to allow access to the jobs runner and/or wheel module
    lpage:
         - .*
         - '@wheel'   # to allow access to all wheel modules
         - '@runner'  # to allow access to all runner modules
         - '@jobs'    # to allow access to the jobs runner and/or wheel module
````
Is this not a suitable permission set? I kind of got lost in that ACL systme improvement page.

Thanks,

**Comment by Lothiraldan** [comment]
I think the `@jobs` permission is redundant with the `@runner` permission, the documentation page is not very explicit

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

Removed the @jobs permission but still can't log in, I'm slightly confused as to your previous comment, are you saying that currently due to a saltstack error we wouldn't be able to log into the saltpad? We don't have anything fancy in our master file just what the default doc states.

Thanks,

**Comment by lukayeh** [comment]
Hi @Lothiraldan 

I was too hasty in my last post, I rebuilt the saltpad install and rebooted the server, and we can now log in, it appears a mix of that and removing @jobs did the trick!

Thank-you for your assistance
